In [27]:
import numpy as np
import matplotlib.pyplot as plt
import MDAnalysis as md
import nglview as ng

In [28]:
u1 = md.Universe('../Rama-Crystal-1/NPT/simfiles/init.gro')
u2 = md.Universe('../Rama-Crystal-1/NPT/simfiles/solvate_genion.gro')

In [29]:
ng.show_mdanalysis(u1, gui=True)

/home/klyshko/anaconda3/lib/python3.6/site-packages/MDAnalysis/coordinates/PDB.py:892: UserWarning: Found no information for attr: 'altLocs' Using default value of ' '
  "".format(attrname, default))
/home/klyshko/anaconda3/lib/python3.6/site-packages/MDAnalysis/coordinates/PDB.py:892: UserWarning: Found no information for attr: 'icodes' Using default value of ' '
  "".format(attrname, default))
/home/klyshko/anaconda3/lib/python3.6/site-packages/MDAnalysis/coordinates/PDB.py:892: UserWarning: Found no information for attr: 'occupancies' Using default value of '1.0'
  "".format(attrname, default))
/home/klyshko/anaconda3/lib/python3.6/site-packages/MDAnalysis/coordinates/PDB.py:892: UserWarning: Found no information for attr: 'tempfactors' Using default value of '0.0'
  "".format(attrname, default))


NGLWidget()

In [30]:
ng.show_mdanalysis(u2, gui=True)

/home/klyshko/anaconda3/lib/python3.6/site-packages/MDAnalysis/coordinates/PDB.py:892: UserWarning: Found no information for attr: 'altLocs' Using default value of ' '
  "".format(attrname, default))
/home/klyshko/anaconda3/lib/python3.6/site-packages/MDAnalysis/coordinates/PDB.py:892: UserWarning: Found no information for attr: 'icodes' Using default value of ' '
  "".format(attrname, default))
/home/klyshko/anaconda3/lib/python3.6/site-packages/MDAnalysis/coordinates/PDB.py:892: UserWarning: Found no information for attr: 'occupancies' Using default value of '1.0'
  "".format(attrname, default))
/home/klyshko/anaconda3/lib/python3.6/site-packages/MDAnalysis/coordinates/PDB.py:892: UserWarning: Found no information for attr: 'tempfactors' Using default value of '0.0'
  "".format(attrname, default))


NGLWidget()

In [69]:
crystal_waters = u1.select_atoms('resname HOH and name OW')

In [70]:
water_coords = crystal_waters.positions

In [71]:
waters2 = u2.select_atoms('resname SOL')

In [72]:
waters2

<AtomGroup with 3477 atoms>

In [73]:
that_water1 = u1.select_atoms('resname HOH and resid 518 and name OW')

In [74]:
this_water2 = u2.select_atoms('resname SOL and resid 631 and name OW')

In [75]:
this_water2.positions

array([[ 29.17    , -11.280001,   8.7     ]], dtype=float32)

In [76]:
that_water1.positions

array([[18.09     , -7.0499997, 25.89     ],
       [50.75     , 12.67     , 25.89     ],
       [29.17     , -7.0499997,  8.7      ],
       [-3.48     , 12.67     ,  8.7      ]], dtype=float32)

In [77]:
crystal_water_coordinates = water_coords

In [78]:
water_coords

array([[21.189999  , 12.57      , -2.9699998 ],
       [ 2.73      ,  9.43      , -0.78000003],
       [ 5.84      ,  4.79      , 10.039999  ],
       ...,
       [-7.7200003 , 29.119999  , 36.55      ],
       [-0.96000004, 21.619999  , 19.119999  ],
       [ 4.44      , 51.39      , 25.02      ]], dtype=float32)

In [79]:
crystal_water_coordinates = water_coords - np.array([0.0, 4.23, 0.0]) 

In [80]:
crystal_water_coordinates

array([[21.18999863,  8.33999969, -2.96999979],
       [ 2.73000002,  5.20000031, -0.78000003],
       [ 5.84000015,  0.55999996, 10.03999901],
       ...,
       [-7.72000027, 24.88999893, 36.54999924],
       [-0.96000004, 17.38999893, 19.11999893],
       [ 4.44000006, 47.15999939, 25.02000046]])

In [82]:
crystal_water_coordinates.shape

(376, 3)