In [61]:
import numpy as np
import matplotlib.pyplot as plt
import MDAnalysis as md
import nglview as ng

In [62]:
u = md.Universe('../crystal_cell/unitcell.pdb')

In [63]:
ng.show_mdanalysis(u, gui=True)

NGLWidget()

In [4]:
atoms = u.select_atoms("all")

In [5]:
params = [63.694000, 38.550999, 38.071999, 90.000000, 117.410004, 90.000000]

In [6]:
a = params[0]
b = params[1]
c = params[2]

alpha = params[3] * np.pi / 180.0
beta = params[4] * np.pi / 180.0
gamma = params[5] * np.pi / 180.0

In [7]:
vec_a = np.array([a, 0.0, 0.0])
vec_b = np.array([b * np.cos(gamma), b * np.sin(gamma), 0.0])
vec_c = np.array([ c * np.cos(beta), c * (np.cos(alpha) - np.cos(beta) * np.cos(gamma))/(np.sin(gamma)) ,
                  c * np.sqrt(1. - np.cos(beta)**2 - ((np.cos(alpha) - np.cos(beta) * np.cos(gamma))/(np.sin(gamma)))**2 )])

In [8]:
vec_a

array([63.694,  0.   ,  0.   ])

In [9]:
vec_b

array([2.36056788e-15, 3.85509990e+01, 0.00000000e+00])

In [10]:
vec_c

array([-1.75266272e+01,  3.40443398e-15,  3.37978468e+01])

In [55]:
u = md.Universe('../../niagara/Rama/crystal_cell/unitcell.pdb')
u0 = md.Universe('../../niagara/Rama/crystal_cell/unitcell.pdb')


A = u1.add_Segment(segid='A_{}'.format(counter));

trans = [-1, 0, 1]
counter = 1
for aa in trans:
    for bb in trans:
        for cc in trans:
            if (aa, bb, cc) != (0, 0, 0): 
                u1 = md.Universe('../../niagara/Rama/crystal_cell/unitcell.pdb')
                A = u1.add_Segment(segid='A{}{}{}'.format(aa + 1, bb + 1, cc + 1));
                B = u1.add_Segment(segid='B{}{}{}'.format(aa + 1, bb + 1, cc + 1));
                C = u1.add_Segment(segid='C{}{}{}'.format(aa + 1, bb + 1, cc + 1));
                D = u1.add_Segment(segid='D{}{}{}'.format(aa + 1, bb + 1, cc + 1));
                
                u1.segments[0].residues.segments = A
                u1.segments[1].residues.segments = B
                u1.segments[2].residues.segments = C
                u1.segments[3].residues.segments = D
                
                counter += 1
                u1.atoms.positions += aa * vec_a + bb * vec_b + cc * vec_c
                u0 = md.Merge(u0.atoms, u1.atoms)
u0.atoms.write('../../niagara/Rama/crystal_cell/uc_{}.pdb'.format(counter))

In [56]:
ng.show_mdanalysis(u0, gui=True)

NGLWidget()

In [57]:
u0.segments.segids

array(['PROA', 'P1PR', 'P2PR', 'P3PR', 'A000', 'B000', 'C000', 'D000',
       'A001', 'B001', 'C001', 'D001', 'A002', 'B002', 'C002', 'D002',
       'A010', 'B010', 'C010', 'D010', 'A011', 'B011', 'C011', 'D011',
       'A012', 'B012', 'C012', 'D012', 'A020', 'B020', 'C020', 'D020',
       'A021', 'B021', 'C021', 'D021', 'A022', 'B022', 'C022', 'D022',
       'A100', 'B100', 'C100', 'D100', 'A101', 'B101', 'C101', 'D101',
       'A102', 'B102', 'C102', 'D102', 'A110', 'B110', 'C110', 'D110',
       'A112', 'B112', 'C112', 'D112', 'A120', 'B120', 'C120', 'D120',
       'A121', 'B121', 'C121', 'D121', 'A122', 'B122', 'C122', 'D122',
       'A200', 'B200', 'C200', 'D200', 'A201', 'B201', 'C201', 'D201',
       'A202', 'B202', 'C202', 'D202', 'A210', 'B210', 'C210', 'D210',
       'A211', 'B211', 'C211', 'D211', 'A212', 'B212', 'C212', 'D212',
       'A220', 'B220', 'C220', 'D220', 'A221', 'B221', 'C221', 'D221',
       'A222', 'B222', 'C222', 'D222'], dtype=object)

In [58]:
newa = a * 3
newb = b * 3
newc = c * 3

In [59]:
cell = [newa, newb, newc, params[3], params[4], params[5]]

In [60]:
cell

[191.082, 115.652997, 114.21599699999999, 90.0, 117.410004, 90.0]